# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            pburke
email:            hi@pburke.de
description:      > 
baseurl:          "/" # the subpath of your site, e.g. /blog
url:              "https://pburke.de" # the base hostname & protocol for your site
twitter_username: burknator
github_username:  burknator

# Build settings
markdown:         kramdown

paginate:         5

gems:
  - emoji_for_jekyll
  - liquid_pluralize
  - liquid_reading_time
  - jekyll-paginate